// Wurks Auto Sales inventory data
// Generated by Wurks Inventory Manager v5.14
window.WURKS_INVENTORY = [
  {
    "id": "2020-subaru-forester-base",
    "status": "Available",
    "year": 2020,
    "make": "Subaru",
    "model": "Forester",
    "trim": "Base",
    "price": "$14,995",
    "miles": 118600,
    "title": "Clean title",
    "drivetrain": "AWD",
    "engine": "4-Cylinder, 2.5L Boxer",
    "transmission": "6-Speed Automatic",
    "fuelEconomy": "26 City / 33 Highway",
    "featured": true,
    "images": [
      "images/2020-subaru-forester-base-01.jpg"
    ],
    "description": "Practical, comfortable, and built for Northern Nevada weather. Subaru symmetrical AWD, roomy interior, and excellent everyday usability.",
    "note": "Overall in great condition. Center armrest shows wear. Mileage may change from normal driving."
  },
  {
    "id": "2019-subaru-forester-sport",
    "year": 2019,
    "make": "Subaru",
    "model": "Forester",
    "trim": "Sport",
    "miles": 90000,
    "title": "Clean title",
    "drivetrain": "AWD",
    "price": "Contact for price",
    "status": "Available",
    "featured": true,
    "image": "",
    "gallery": [],
    "description": "Forester Sport styling with Subaru AWD, useful cargo space, and the confidence that makes these vehicles popular in Northern Nevada.",
    "note": "Clean title and no reported accidents based on current dealership information.",
    "images": []
  },
  {
    "id": "2010-volkswagen-cc-vr6",
    "status": "Sold",
    "year": 2010,
    "make": "Volkswagen",
    "model": "CC",
    "trim": "3.6 VR6 4Motion",
    "price": "Contact for price",
    "miles": 96400,
    "title": "Clean title",
    "drivetrain": "AWD",
    "featured": true,
    "images": [
      "images/2010-volkswagen-cc-vr6-01.jpg",
      "images/2010-volkswagen-cc-vr6-02.jpg",
      "images/2010-volkswagen-cc-vr6-03.jpg",
      "images/2010-volkswagen-cc-vr6-04.jpg"
    ],
    "description": "A rare enthusiast-oriented CC with the 3.6-liter VR6 and 4Motion all-wheel drive. Comfortable, distinctive, and more interesting than the average sedan.",
    "note": "Previously described as having no mechanical issues and only minimal cosmetic imperfections. Confirm current availability before publishing."
  },
  {
    "id": "2013-bmw-x5-xdrive50i",
    "year": 2013,
    "make": "BMW",
    "model": "X5",
    "trim": "xDrive50i",
    "miles": 140014,
    "title": "Clean title",
    "drivetrain": "AWD",
    "price": "Contact for price",
    "status": "Coming Soon",
    "featured": true,
    "image": "images/bmw-x5-1.jpg",
    "gallery": [
      "images/bmw-x5-2.jpg",
      "images/bmw-x5-3.jpg"
    ],
    "description": "Twin-turbo V8 power, a comfortable ride, and classic BMW SUV driving feel. Strong performance with a well-kept interior.",
    "note": "Known smoke-at-idle condition previously disclosed; it goes away during normal driving and the vehicle was reported to pass smog. Sold as-is. Confirm current availability before publishing.",
    "images": [
      "images/bmw-x5-1.jpg",
      "images/bmw-x5-2.jpg",
      "images/bmw-x5-3.jpg"
    ]
  }
];
